[package]
name = "error"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gloo = "0.11.0"
ron = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.117"
js-sys = "0.3.63"
tauri-sys = { workspace = true }